name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root # Replace with your VPS username
        key: ${{ secrets.SSH_PRIVATE_KEY_SECRET_NAME }}  # Reference secret name
        script: |
          cd /home/<your_deployment_user>/rental-car/FER-17-PLATINUM-ADMIN
          git pull origin main
          npm install >> install.log 2>&1
          npm run build >> build.log 2>&1
          # Adjust the following command if pm2 is not available/desired
          sudo pm2 reload ecosystem.config.js --only FER-17-PLATINUM-ADMIN
        debug: true
