name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /root/rental-car/FER-17-PLATINUM-ADMIN
          git pull origin main
          npm install
          npm run build
          pm2 reload ecosystem.config.js --only FER-17-PLATINUM-ADMIN
        debug: true
