# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS
      uses: easingthemes/ssh-deploy@main
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
         cd /root/rental-car/FER-17-PLATINUM-ADMIN
         git pull origin main
         npm install >> install.log 2>&1  # Capture npm install output
         npm run build >> build.log 2>&1  # Capture npm run build output
         pm2 reload ecosystem.config.js --only FER-17-PLATINUM-ADMIN
        debug: true
